
import React, { useState, useEffect, useRef, useCallback } from 'react';
import { BookOpen, HelpCircle, Video, FileText, ChevronDown, ChevronUp, PlayCircle, ExternalLink, Zap, Shield, Terminal, LifeBuoy, ArrowLeft, CheckCircle, Clock, Play, Pause, Volume2, Maximize, MousePointer2, Plus, LayoutDashboard, Server, X, RefreshCw } from 'lucide-react';

const TUTORIALS = [
    {
        id: 1,
        title: "Quick Start: First Deployment",
        description: "Learn how to flash a Raspberry Pi, run the bootstrap script, and enroll your first actor into the fleet.",
        time: "5 min",
        level: "Beginner",
        icon: Terminal,
        color: "text-blue-400",
        bg: "bg-blue-500/10",
        border: "border-blue-500/30",
        steps: [
            { title: "Prepare the Hardware", text: "Ensure your Raspberry Pi (3B+ or 4) has a fresh install of Raspberry Pi OS Lite (64-bit recommended) and internet access." },
            { title: "Generate Enrollment Token", text: "In the Dashboard sidebar, click 'Enroll New Device'. Select 'Direct to Cloud' or a specific Gateway." },
            { title: "Run Bootstrap Command", text: "Copy the provided curl command. Paste it into your Raspberry Pi terminal via SSH.", code: "curl -sL http://vpp.io/api/setup?token=YOUR_TOKEN | sudo bash" },
            { title: "Approve Device", text: "Once the script finishes, the device will appear in 'Pending Approvals'. Click the Green checkmark to adopt it." }
        ]
    },
    {
        id: 2,
        title: "Mastering Personas",
        description: "How to switch device identities (e.g., from Printer to PLC) to deceive different types of attackers.",
        time: "3 min",
        level: "Intermediate",
        icon: Zap,
        color: "text-purple-400",
        bg: "bg-purple-500/10",
        border: "border-purple-500/30",
        steps: [
            { title: "Select Target Actor", text: "Navigate to the 'Fleet Matrix' or Dashboard and click on an online node to open details." },
            { title: "Open Deception Tab", text: "Switch to the 'DECEPTION & PERSONA' tab in the top navigation bar." },
            { title: "Choose Identity", text: "Review available Personas (Printer, Camera, Server). Note any port conflicts marked in red." },
            { title: "Apply & Verify", text: "Click a Persona. The agent will restart networking, spoof the MAC OUI, and open fake ports. Use Nmap externally to verify." }
        ]
    },
    {
        id: 3,
        title: "Sentinel Mode & Lockdowns",
        description: "Understanding the 'Paranoid' TCP Sentinel mode and when to use it during an active breach.",
        time: "4 min",
        level: "Advanced",
        icon: Shield,
        color: "text-red-400",
        bg: "bg-red-500/10",
        border: "border-red-500/30",
        steps: [
            { title: "Understanding Sentinel", text: "Sentinel Mode configures iptables to log EVERY TCP SYN packet. This is noisy but catches stealth scans." },
            { title: "Activation", text: "In the 'NETWORK' tab of an actor, toggle 'TCP Sentinel (Paranoid Mode)'. The dashboard will show a pulsing eye icon." },
            { title: "Monitoring", text: "Go to the Dashboard Overview. Any connection attempt will immediately trigger a CRITICAL alert and visualize the source IP." },
            { title: "Deactivation", text: "Once the threat is identified, disable Sentinel Mode to reduce log volume and return to standard honeypot operations." }
        ]
    },
    {
        id: 4,
        title: "Analyzing Forensic Snapshots",
        description: "A deep dive into reading memory dumps, process trees, and auth logs generated by the forensic tool.",
        time: "8 min",
        level: "Expert",
        icon: FileText,
        color: "text-emerald-400",
        bg: "bg-emerald-500/10",
        border: "border-emerald-500/30",
        steps: [
            { title: "Trigger Snapshot", text: "In the 'FORENSICS' tab, click 'RUN FORENSIC SCAN'. This commands the agent to dump volatile data." },
            { title: "Process Tree Analysis", text: "Look for processes with high CPU usage or names like 'nc', 'bash' (running as www-data), or crypto miners." },
            { title: "Network Connections", text: "Examine the 'Network Artifacts' section. Look for ESTABLISHED connections to unknown external IPs on non-standard ports." },
            { title: "Persistence Check", text: "Review the Auth Log snippet for 'Accepted password' or 'New session' events you didn't authorize." }
        ]
    }
];

const FAQS = [
    {
        q: "What exactly does the Virtual Puppets agent do?",
        a: "The agent (vpp-agent) is a lightweight daemon that runs on Linux devices (typically Raspberry Pis). It manages local iptables for traffic control, establishes reverse tunnels to the C2 server, and can emulate various services (SSH, HTTP, FTP) to trap attackers. It also collects telemetry like CPU usage and wireless signals."
    },
    {
        q: "How do I reset a 'Compromised' node?",
        a: "If a node is flagged as COMPROMISED, go to the Actor Detail view. You can either click 'Acknowledge Alert' to simply clear the status if it was a false positive, or use 'Factory Reset' to wipe the agent's local state, clear tunnels, and restart networking."
    },
    {
        q: "Is the traffic real or simulated?",
        a: "In 'Production' mode (connected to a database), the traffic logs are real events reported by your agents. In 'Mock' mode, the system generates simulated traffic patterns for demonstration and training purposes."
    },
    {
        q: "What network ports does the agent require?",
        a: "The agent primarily needs outbound HTTPS (TCP/443) access to the C2 server API. If using Tunneling/Traps, it may also require outbound TCP connections on ephemeral ports to the Trap Server. No inbound port forwarding on your firewall is strictly necessary for standard operation."
    },
    {
        q: "Can I run this on a VM instead of a Raspberry Pi?",
        a: "Yes! The installation script supports Ubuntu 20.04+, Debian 11+, and Kali Linux. You can deploy it on AWS EC2, a local VM, or even a Docker container (with --privileged mode for iptables access)."
    },
    {
        q: "What is 'Ghost Mode'?",
        a: "Ghost Mode is a high-interaction session recorder. When an attacker interacts with a projected Trap (like a fake Telnet service), the session is recorded keystroke-by-keystroke. You can replay these sessions in the Forensics tab to understand the attacker's methodology."
    }
];

// --- MOCK UI COMPONENTS FOR THE VIDEO ---

const MockDashboard = ({ 
    activeModal, 
    pendingCount, 
    actors 
}: { activeModal: string | null, pendingCount: number, actors: any[] }) => (
    <div className="h-full w-full bg-slate-900 flex text-[8px] md:text-[10px] font-sans overflow-hidden select-none">
        {/* Sidebar */}
        <div className="w-16 bg-slate-950 border-r border-slate-800 flex flex-col items-center py-4 space-y-4">
            <div className="w-8 h-8 rounded bg-blue-900/50 mb-2"></div>
            <div className="w-8 h-8 rounded bg-slate-800 flex items-center justify-center text-slate-500"><LayoutDashboard className="w-4 h-4"/></div>
            <div className="w-8 h-8 rounded bg-slate-800 flex items-center justify-center text-slate-500"><Server className="w-4 h-4"/></div>
            <div className="w-8 h-8 rounded bg-slate-800 flex items-center justify-center text-slate-500"><Plus className="w-4 h-4"/></div>
        </div>
        {/* Main Content */}
        <div className="flex-1 p-4 bg-slate-900/90 relative">
            <div className="flex justify-between items-center mb-4">
                <div className="h-4 w-32 bg-slate-800 rounded"></div>
                <div className="bg-blue-600 text-white px-2 py-1 rounded flex items-center shadow-lg cursor-pointer" id="btn-enroll">
                    <Plus className="w-3 h-3 mr-1" /> Enroll
                </div>
            </div>
            {/* Grid */}
            <div className="grid grid-cols-3 gap-2">
                {actors.map(a => (
                    <div key={a.id} className={`h-16 rounded border p-2 ${a.status === 'ONLINE' ? 'bg-slate-800 border-slate-700' : 'bg-red-900/20 border-red-500'}`}>
                        <div className="flex justify-between mb-1">
                            <div className="w-4 h-4 rounded bg-slate-700"></div>
                            <div className={`w-2 h-2 rounded-full ${a.status === 'ONLINE' ? 'bg-emerald-500' : 'bg-red-500'}`}></div>
                        </div>
                        <div className="h-2 w-16 bg-slate-700 rounded mb-1"></div>
                        <div className="h-2 w-10 bg-slate-700/50 rounded"></div>
                    </div>
                ))}
            </div>

            {/* Simulated Modal */}
            {activeModal === 'ENROLL' && (
                <div className="absolute inset-0 bg-black/60 flex items-center justify-center backdrop-blur-[1px] animate-fade-in z-20">
                    <div className="bg-slate-800 border border-slate-600 rounded p-4 w-3/4 shadow-2xl">
                        <div className="flex justify-between mb-3 border-b border-slate-700 pb-2">
                            <span className="text-white font-bold">Enroll New Device</span>
                            <X className="w-3 h-3 text-slate-500" />
                        </div>
                        <div className="bg-black p-2 rounded border border-slate-700 mb-3 font-mono text-emerald-400 truncate flex justify-between items-center">
                            <span>curl -sL http://vpp.io/setup | bash</span>
                            <span className="bg-slate-700 text-white px-1 rounded ml-2 cursor-pointer hover:bg-slate-600" id="btn-copy">Copy</span>
                        </div>
                        <div className="border-t border-slate-700 pt-2">
                            <div className="flex justify-between items-center">
                                <span className="text-slate-400">Pending Devices</span>
                                {pendingCount > 0 ? (
                                    <span className="bg-blue-600 text-white px-1.5 rounded animate-pulse">{pendingCount} New</span>
                                ) : <span className="text-slate-600">Waiting...</span>}
                            </div>
                            {pendingCount > 0 && (
                                <div className="mt-2 bg-slate-900 p-2 rounded flex justify-between items-center border border-slate-700">
                                    <div className="flex items-center">
                                        <Terminal className="w-3 h-3 text-yellow-500 mr-2"/>
                                        <span>New_Pi_Device</span>
                                    </div>
                                    <div className="bg-emerald-600 p-1 rounded text-white cursor-pointer hover:bg-emerald-500" id="btn-approve">
                                        <CheckCircle className="w-3 h-3"/>
                                    </div>
                                </div>
                            )}
                        </div>
                    </div>
                </div>
            )}
        </div>
    </div>
);

// --- ANIMATION ORCHESTRATOR ---

const PlayerEngine = ({ scenario, onFinish }: { scenario: any, onFinish: () => void }) => {
    // VISUAL STATE
    const [cursor, setCursor] = useState({ x: 50, y: 50, clicking: false });
    const [layout, setLayout] = useState<'TERMINAL' | 'DASHBOARD' | 'SPLIT'>('DASHBOARD');
    const [terminalLines, setTerminalLines] = useState<string[]>([]);
    
    // DASHBOARD STATE
    const [activeModal, setActiveModal] = useState<string | null>(null);
    const [pendingCount, setPendingCount] = useState(0);
    const [mockActors, setMockActors] = useState([{id:1, status:'ONLINE'}, {id:2, status:'ONLINE'}, {id:3, status:'OFFLINE'}]);

    // Refs for safe async loop
    const isMounted = useRef(true);

    // Helpers
    const wait = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));
    const typeLine = async (text: string) => {
        if(!isMounted.current) return;
        setTerminalLines(prev => [...prev, ""]);
        // Typing effect
        for(let i=0; i<text.length; i++) {
            if(!isMounted.current) return;
            setTerminalLines(prev => {
                const copy = [...prev];
                copy[copy.length-1] = text.substring(0, i+1);
                return copy;
            });
            await wait(20 + Math.random() * 30);
        }
        await wait(200);
    };

    const moveMouseTo = async (targetX: number, targetY: number, duration: number = 800) => {
        if(!isMounted.current) return;
        const startX = cursor.x;
        const startY = cursor.y;
        const startTime = Date.now();

        return new Promise<void>(resolve => {
            const animate = () => {
                if(!isMounted.current) return resolve();
                const now = Date.now();
                const progress = Math.min(1, (now - startTime) / duration);
                
                // Ease out cubic
                const ease = 1 - Math.pow(1 - progress, 3);
                
                setCursor(prev => ({
                    ...prev,
                    x: startX + (targetX - startX) * ease,
                    y: startY + (targetY - startY) * ease
                }));

                if (progress < 1) {
                    requestAnimationFrame(animate);
                } else {
                    resolve();
                }
            };
            requestAnimationFrame(animate);
        });
    };

    const click = async () => {
        if(!isMounted.current) return;
        setCursor(prev => ({...prev, clicking: true}));
        await wait(150);
        setCursor(prev => ({...prev, clicking: false}));
        await wait(300);
    };

    // --- SCENARIO LOGIC ---
    useEffect(() => {
        const runScenario = async () => {
            if (scenario.id === 1) { // QUICK START
                // 1. Initial State
                setLayout('DASHBOARD');
                setMockActors([{id:1, status:'ONLINE'}]);
                await wait(1000);

                // 2. Click Enroll
                await moveMouseTo(85, 12); 
                await click();
                setActiveModal('ENROLL');
                await wait(800);

                // 3. Copy Command
                await moveMouseTo(88, 38);
                await click(); // Copy
                await wait(500);

                // 4. Switch to Split View (Show Terminal)
                setLayout('SPLIT');
                await wait(800);

                // 5. Run Command in Terminal
                await typeLine("pi@raspberry:~ $ curl -sL http://vpp.io/setup | sudo bash");
                await wait(500);
                await typeLine("[+] Downloading Agent...");
                await typeLine("[+] Installing Dependencies...");
                await wait(1000);
                await typeLine("[+] Connecting to C2...");
                await wait(500);
                
                // 6. Device Appears
                setPendingCount(1);
                await typeLine("[!] Waiting for approval...");
                
                // 7. Approve on Dashboard (Right side of split is terminal, Left is Dash)
                // Mouse needs to go to Left side relative to whole container
                await moveMouseTo(42, 65); // Coordinates for Approve button in split mode
                await click();
                
                // 8. Success
                setPendingCount(0);
                setActiveModal(null);
                setMockActors(prev => [...prev, {id:2, status:'ONLINE'}]);
                await typeLine("[OK] Device Adopted!");
                await typeLine("[OK] Starting Service...");
                
                await wait(2000);
                if(isMounted.current) onFinish();
            } 
            else if (scenario.id === 2) { // PERSONAS
                // 1. Dash View
                setLayout('DASHBOARD');
                await wait(500);
                
                // 2. Click Actor
                await moveMouseTo(20, 20); // First actor grid
                await click();
                
                // 3. Simulate Tab Switch (simplified visually)
                // We'll just show terminal typing "Switching..."
                setLayout('SPLIT');
                await typeLine("root@node:~ $ vpp-agent --set-persona 'Printer'");
                await typeLine("[+] Stopping HTTP...");
                await typeLine("[+] Opening Port 9100...");
                await typeLine("[OK] Persona Applied: HP LaserJet");
                await wait(2000);
                if(isMounted.current) onFinish();
            }
            else {
                // Fallback for others
                setLayout('TERMINAL');
                await typeLine("Running simulated scenario...");
                await typeLine("Step 1 complete.");
                await typeLine("Step 2 complete.");
                await wait(2000);
                if(isMounted.current) onFinish();
            }
        };

        runScenario();

        return () => { isMounted.current = false; };
    }, [scenario]);

    return (
        <div className="relative w-full h-full bg-black overflow-hidden flex">
            
            {/* LEFT PANE (Dashboard) */}
            <div className={`relative transition-all duration-500 ease-in-out border-r border-slate-800 ${layout === 'TERMINAL' ? 'w-0' : layout === 'SPLIT' ? 'w-1/2' : 'w-full'}`}>
                <MockDashboard activeModal={activeModal} pendingCount={pendingCount} actors={mockActors} />
            </div>

            {/* RIGHT PANE (Terminal) */}
            <div className={`relative bg-black transition-all duration-500 ease-in-out ${layout === 'DASHBOARD' ? 'w-0' : layout === 'SPLIT' ? 'w-1/2' : 'w-full'}`}>
                <div className="absolute inset-0 p-4 font-mono text-[10px] md:text-xs text-green-500 overflow-hidden">
                    {terminalLines.map((line, i) => (
                        <div key={i} className="mb-1 break-all">{line}</div>
                    ))}
                    <span className="inline-block w-2 h-4 bg-green-500 animate-pulse ml-1 align-middle"></span>
                </div>
            </div>

            {/* CURSOR OVERLAY */}
            <div 
                className="absolute pointer-events-none z-50 transition-transform duration-75"
                style={{ 
                    left: `${cursor.x}%`, 
                    top: `${cursor.y}%`,
                    transform: `translate(-50%, -50%) scale(${cursor.clicking ? 0.8 : 1})`
                }}
            >
                <MousePointer2 
                    className="w-6 h-6 text-white drop-shadow-[0_2px_4px_rgba(0,0,0,0.5)] fill-black" 
                    strokeWidth={1.5}
                />
                {cursor.clicking && (
                    <div className="absolute -inset-2 bg-white/30 rounded-full animate-ping"></div>
                )}
            </div>

            {/* LAYOUT BADGE */}
            <div className="absolute top-2 right-2 bg-slate-800/80 px-2 py-1 rounded text-[8px] text-slate-400 font-mono border border-slate-700 backdrop-blur">
                MODE: {layout}
            </div>
        </div>
    );
};

// --- WRAPPER PLAYER COMPONENT ---
const MockPlayer = ({ tutorial }: { tutorial: any }) => {
    const [isPlaying, setIsPlaying] = useState(false);
    const [resetKey, setResetKey] = useState(0);

    const handleRestart = () => {
        setIsPlaying(false);
        setTimeout(() => {
            setResetKey(p => p + 1);
            setIsPlaying(true);
        }, 100);
    };

    return (
        <div className="w-full aspect-video bg-black rounded-lg border border-slate-700 relative group overflow-hidden shadow-2xl flex flex-col">
            {/* Screen Content */}
            <div className="flex-1 bg-slate-900 relative overflow-hidden">
                {!isPlaying ? (
                    <div className="absolute inset-0 flex flex-col items-center justify-center bg-slate-900/50 backdrop-blur-sm z-10">
                        <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/carbon-fibre.png')] opacity-20 pointer-events-none"></div>
                        <button 
                            onClick={handleRestart}
                            className="w-20 h-20 bg-blue-600/90 rounded-full flex items-center justify-center shadow-[0_0_30px_rgba(37,99,235,0.3)] hover:scale-110 transition-transform z-10 group/play"
                        >
                            <Play className="w-10 h-10 text-white ml-1.5 group-hover/play:scale-110 transition-transform" />
                        </button>
                        <div className="mt-4 text-white font-bold text-lg drop-shadow-md bg-black/50 px-3 py-1 rounded border border-white/10 flex items-center">
                            <Video className="w-4 h-4 mr-2 text-blue-400" />
                            {tutorial.title}
                        </div>
                    </div>
                ) : (
                    <PlayerEngine key={resetKey} scenario={tutorial} onFinish={() => setIsPlaying(false)} />
                )}
            </div>

            {/* Controls Bar */}
            <div className="h-10 bg-slate-800 border-t border-slate-700 flex items-center px-4 space-x-4 z-20 select-none">
                <button onClick={() => setIsPlaying(!isPlaying)} className="text-slate-300 hover:text-white transition-colors">
                    {isPlaying ? <Pause className="w-4 h-4" /> : <Play className="w-4 h-4" />}
                </button>
                <div className="flex-1 h-1 bg-slate-600 rounded-full overflow-hidden">
                    <div className={`h-full bg-blue-500 transition-all duration-300 ${isPlaying ? 'w-full transition-[width] duration-[10000ms] ease-linear' : 'w-0'}`}></div>
                </div>
                <button onClick={handleRestart} className="text-slate-300 hover:text-white" title="Restart">
                    <RefreshCw className="w-4 h-4" />
                </button>
            </div>
        </div>
    );
};

const HelpCenter = () => {
    const [activeTab, setActiveTab] = useState<'TUTORIALS' | 'FAQ'>('TUTORIALS');
    const [openFaqIndex, setOpenFaqIndex] = useState<number | null>(0);
    const [selectedTutorial, setSelectedTutorial] = useState<any>(null);

    return (
        <div className="p-6 max-w-6xl mx-auto animate-fade-in h-full flex flex-col">
            
            {/* HEADER */}
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-8 shrink-0">
                {!selectedTutorial ? (
                    <div>
                        <h2 className="text-3xl font-bold text-slate-200 flex items-center">
                            <LifeBuoy className="w-8 h-8 mr-3 text-blue-400" />
                            Help & Knowledge Base
                        </h2>
                        <p className="text-slate-500 text-sm mt-1">Documentation, guides, and support resources for Virtual Puppets.</p>
                    </div>
                ) : (
                    <div className="flex items-center">
                        <button 
                            onClick={() => setSelectedTutorial(null)}
                            className="bg-slate-800 hover:bg-slate-700 p-2 rounded-full mr-4 text-slate-400 hover:text-white transition-colors border border-slate-700"
                        >
                            <ArrowLeft className="w-5 h-5" />
                        </button>
                        <div>
                            <div className="flex items-center space-x-3 mb-1">
                                <span className={`px-2 py-0.5 rounded text-[10px] font-bold uppercase border ${selectedTutorial.bg} ${selectedTutorial.color} ${selectedTutorial.border}`}>
                                    {selectedTutorial.level}
                                </span>
                                <span className="text-slate-500 text-xs flex items-center"><Clock className="w-3 h-3 mr-1"/> {selectedTutorial.time} Read</span>
                            </div>
                            <h2 className="text-2xl font-bold text-white">{selectedTutorial.title}</h2>
                        </div>
                    </div>
                )}

                {!selectedTutorial && (
                    <div className="flex space-x-4 mt-4 md:mt-0">
                        <button 
                            onClick={() => setActiveTab('TUTORIALS')}
                            className={`px-6 py-2 rounded-lg font-bold text-sm transition-all flex items-center ${activeTab === 'TUTORIALS' ? 'bg-blue-600 text-white shadow-lg shadow-blue-900/20' : 'bg-slate-800 text-slate-400 hover:text-white'}`}
                        >
                            <Video className="w-4 h-4 mr-2" /> Tutorials
                        </button>
                        <button 
                            onClick={() => setActiveTab('FAQ')}
                            className={`px-6 py-2 rounded-lg font-bold text-sm transition-all flex items-center ${activeTab === 'FAQ' ? 'bg-blue-600 text-white shadow-lg shadow-blue-900/20' : 'bg-slate-800 text-slate-400 hover:text-white'}`}
                        >
                            <HelpCircle className="w-4 h-4 mr-2" /> Q & A
                        </button>
                    </div>
                )}
            </div>

            <div className="flex-1 overflow-y-auto pr-2 pb-10">
                {activeTab === 'TUTORIALS' && !selectedTutorial && (
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        {/* Featured Video Placeholder */}
                        <div className="md:col-span-2 bg-slate-900 rounded-xl border border-slate-700 overflow-hidden relative group cursor-pointer aspect-video md:aspect-[3/1]">
                            <div className="absolute inset-0 bg-gradient-to-r from-slate-900 to-transparent z-10"></div>
                            {/* Mock Video UI */}
                            <div className="absolute inset-0 flex items-center justify-center z-20">
                                <div className="w-16 h-16 bg-blue-600/90 rounded-full flex items-center justify-center shadow-2xl group-hover:scale-110 transition-transform">
                                    <PlayCircle className="w-8 h-8 text-white ml-1" />
                                </div>
                            </div>
                            <div className="absolute bottom-0 left-0 p-8 z-20 max-w-2xl">
                                <span className="bg-blue-600 text-white text-xs font-bold px-2 py-1 rounded mb-3 inline-block">NEW FEATURE</span>
                                <h3 className="text-2xl font-bold text-white mb-2">Introduction to Wireless Reconnaissance</h3>
                                <p className="text-slate-300 text-sm">Learn how to use your deployed agents to passively map nearby Wi-Fi networks and Bluetooth devices to detect physical threats.</p>
                            </div>
                            {/* Background Pattern */}
                            <div className="absolute inset-0 opacity-20 bg-[url('https://www.transparenttextures.com/patterns/cubes.png')]"></div>
                        </div>

                        {TUTORIALS.map((tut) => (
                            <div 
                                key={tut.id} 
                                onClick={() => setSelectedTutorial(tut)}
                                className={`p-6 rounded-xl border ${tut.border} bg-slate-800/50 hover:bg-slate-800 transition-all cursor-pointer group relative overflow-hidden`}
                            >
                                <div className={`absolute top-0 right-0 p-3 opacity-10 group-hover:opacity-20 transition-opacity`}>
                                    <tut.icon className="w-24 h-24" />
                                </div>
                                <div className="flex justify-between items-start mb-4 relative z-10">
                                    <div className={`p-3 rounded-lg ${tut.bg}`}>
                                        <tut.icon className={`w-6 h-6 ${tut.color}`} />
                                    </div>
                                    <span className="text-[10px] uppercase font-bold tracking-wider text-slate-500 bg-slate-900 px-2 py-1 rounded border border-slate-700">{tut.level}</span>
                                </div>
                                <h3 className="text-lg font-bold text-white mb-2 relative z-10 group-hover:text-blue-400 transition-colors">{tut.title}</h3>
                                <p className="text-slate-400 text-sm mb-4 relative z-10 h-10 line-clamp-2">{tut.description}</p>
                                <div className="flex items-center text-xs text-slate-500 font-mono relative z-10">
                                    <span className="flex items-center mr-4"><Video className="w-3 h-3 mr-1" /> {tut.time}</span>
                                    <span className="flex items-center text-blue-400 opacity-0 group-hover:opacity-100 transition-opacity">Start Guide &rarr;</span>
                                </div>
                            </div>
                        ))}
                    </div>
                )}

                {/* TUTORIAL DETAIL VIEW */}
                {activeTab === 'TUTORIALS' && selectedTutorial && (
                    <div className="animate-slide-up space-y-8">
                        {/* Video Player Area */}
                        <MockPlayer tutorial={selectedTutorial} />

                        {/* Content Area */}
                        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                            <div className="lg:col-span-2 space-y-6">
                                <div className="bg-slate-800/50 border border-slate-700 rounded-xl p-6">
                                    <h3 className="text-lg font-bold text-white mb-4">Step-by-Step Guide</h3>
                                    <div className="space-y-6">
                                        {selectedTutorial.steps?.map((step: any, idx: number) => (
                                            <div key={idx} className="flex gap-4">
                                                <div className="flex flex-col items-center">
                                                    <div className={`w-8 h-8 rounded-full flex items-center justify-center font-bold text-sm shrink-0 ${idx === 0 ? 'bg-blue-600 text-white' : 'bg-slate-700 text-slate-300'}`}>
                                                        {idx + 1}
                                                    </div>
                                                    {idx < selectedTutorial.steps.length - 1 && (
                                                        <div className="w-0.5 flex-1 bg-slate-700 my-2"></div>
                                                    )}
                                                </div>
                                                <div className="pb-2">
                                                    <h4 className="text-white font-bold text-sm mb-1">{step.title}</h4>
                                                    <p className="text-slate-400 text-sm leading-relaxed">{step.text}</p>
                                                    {step.code && (
                                                        <div className="mt-3 bg-black rounded border border-slate-700 p-3 group relative">
                                                            <code className="text-emerald-400 font-mono text-xs break-all">{step.code}</code>
                                                            <button 
                                                                onClick={() => navigator.clipboard.writeText(step.code)}
                                                                className="absolute top-2 right-2 bg-slate-800 p-1.5 rounded text-slate-400 hover:text-white opacity-0 group-hover:opacity-100 transition-opacity"
                                                                title="Copy"
                                                            >
                                                                <CheckCircle className="w-3 h-3" />
                                                            </button>
                                                        </div>
                                                    )}
                                                </div>
                                            </div>
                                        ))}
                                    </div>
                                </div>
                            </div>

                            {/* Sidebar Info */}
                            <div className="space-y-4">
                                <div className="bg-blue-900/20 border border-blue-500/30 rounded-xl p-5">
                                    <h4 className="text-blue-400 font-bold text-sm mb-2 flex items-center"><Zap className="w-4 h-4 mr-2"/> Key Takeaways</h4>
                                    <ul className="text-xs text-blue-200 space-y-2 list-disc list-inside">
                                        <li>Always verify connectivity after deployment.</li>
                                        <li>Use Personas to match the physical environment.</li>
                                        <li>Sentinel mode generates high log volume.</li>
                                    </ul>
                                </div>
                                
                                <div className="bg-slate-800 border border-slate-700 rounded-xl p-5">
                                    <h4 className="text-white font-bold text-sm mb-3">Related Topics</h4>
                                    <ul className="space-y-2">
                                        {TUTORIALS.filter(t => t.id !== selectedTutorial.id).slice(0,3).map(t => (
                                            <li key={t.id}>
                                                <button 
                                                    onClick={() => setSelectedTutorial(t)}
                                                    className="text-xs text-slate-400 hover:text-blue-400 flex items-center transition-colors text-left"
                                                >
                                                    <PlayCircle className="w-3 h-3 mr-2 shrink-0" />
                                                    {t.title}
                                                </button>
                                            </li>
                                        ))}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                )}

                {activeTab === 'FAQ' && (
                    <div className="max-w-4xl mx-auto space-y-4">
                        <div className="bg-blue-900/20 border border-blue-500/30 p-4 rounded-lg mb-6 flex items-start">
                            <BookOpen className="w-5 h-5 text-blue-400 mr-3 mt-0.5" />
                            <div>
                                <h4 className="text-blue-300 font-bold text-sm mb-1">Documentation Library</h4>
                                <p className="text-blue-200/70 text-xs">For detailed API references, architecture diagrams, and security whitepapers, please visit our internal wiki.</p>
                                <a href="#" className="text-blue-400 text-xs font-bold mt-2 inline-flex items-center hover:underline">Open Wiki <ExternalLink className="w-3 h-3 ml-1"/></a>
                            </div>
                        </div>

                        {FAQS.map((faq, index) => {
                            const isOpen = openFaqIndex === index;
                            return (
                                <div key={index} className={`border rounded-lg transition-all duration-300 overflow-hidden ${isOpen ? 'bg-slate-800 border-blue-500/50' : 'bg-slate-900 border-slate-700 hover:border-slate-600'}`}>
                                    <button 
                                        onClick={() => setOpenFaqIndex(isOpen ? null : index)}
                                        className="w-full flex justify-between items-center p-4 text-left focus:outline-none"
                                    >
                                        <span className={`font-bold text-sm ${isOpen ? 'text-blue-400' : 'text-slate-300'}`}>{faq.q}</span>
                                        {isOpen ? <ChevronUp className="w-4 h-4 text-blue-500" /> : <ChevronDown className="w-4 h-4 text-slate-500" />}
                                    </button>
                                    {isOpen && (
                                        <div className="px-4 pb-4 text-slate-400 text-sm leading-relaxed border-t border-slate-700/50 pt-3 animate-fade-in">
                                            {faq.a}
                                        </div>
                                    )}
                                </div>
                            );
                        })}

                        <div className="mt-12 text-center pt-8 border-t border-slate-800">
                            <p className="text-slate-500 text-sm mb-4">Still need help? Our security engineers are available 24/7.</p>
                            <button className="bg-slate-800 hover:bg-slate-700 text-white px-6 py-2 rounded-full font-bold text-sm transition-colors border border-slate-600">
                                Contact Support
                            </button>
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
};

export default HelpCenter;
